security:
    encoders:
        Samson\Bundle\SecurityBundle\Entity\User:
          algorithm: md5
          iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Samson\Bundle\SecurityBundle\Entity\User, property: username }

    firewalls:
        secured_area:
            pattern:    ^/
            security: false

    acl:
       connection: default